/*
 * This file is generated by jOOQ.
 */
package demo.webauthn;


import demo.webauthn.tables.Users;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>webauthn_demo</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USERS_USERNAME_AND_PASSWORD = Indexes0.USERS_USERNAME_AND_PASSWORD;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index USERS_USERNAME_AND_PASSWORD = Internal.createIndex("username_and_password", Users.USERS, new OrderField[] { Users.USERS.USERNAME, Users.USERS.PASSWORD_BCRYPT }, false);
    }
}
