/*
 * This file is generated by jOOQ.
 */
package demo.webauthn;


import demo.webauthn.tables.Users;
import demo.webauthn.tables.WebauthnCredentials;


/**
 * Convenience access to all tables in webauthn_demo
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>webauthn_demo.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>webauthn_demo.webauthn_credentials</code>.
     */
    public static final WebauthnCredentials WEBAUTHN_CREDENTIALS = WebauthnCredentials.WEBAUTHN_CREDENTIALS;
}
