/*
 * This file is generated by jOOQ.
 */
package demo.webauthn;


import demo.webauthn.tables.Users;


/**
 * Convenience access to all tables in webauthn_demo
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>webauthn_demo.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
