/*
 * This file is generated by jOOQ.
 */
package demo.webauthn;


import demo.webauthn.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WebauthnDemo extends SchemaImpl {

    private static final long serialVersionUID = 1641950546;

    /**
     * The reference instance of <code>webauthn_demo</code>
     */
    public static final WebauthnDemo WEBAUTHN_DEMO = new WebauthnDemo();

    /**
     * The table <code>webauthn_demo.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private WebauthnDemo() {
        super("webauthn_demo", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Users.USERS);
    }
}
